<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>org.jrimum</groupId>
	<artifactId>bopepo</artifactId>
	<packaging>jar</packaging>
	<name>Projeto Bopepo</name>
	<version>0.3.3-20261002</version>
	<description>Projeto open source de componentes de software para o domínio de negócios do Brasil.</description>
	<url>http://www.jrimum.org/bopepo</url>

	<repositories>
		<repository>
			<id>brax-nexus-public-group</id>
			<url>http://dev.brax.com.br:8081/nexus/content/groups/public/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>never</updatePolicy>
			</snapshots>
		</repository>
	</repositories>

	<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<organization>
		<name>Grupo JRimum</name>
		<url>http://www.jrimum.org/</url>
	</organization>

	<issueManagement>
		<system>TRAC</system>
		<url>http://www.jrimum.org/bopepo</url>
	</issueManagement>

	<ciManagement>
		<system>hudson</system>
		<url>http://localhost:8080/hudson</url>
	</ciManagement>

	<scm>
		<connection>scm:svn:http://www.jrimum.org/svn/bopepo</connection>
		<developerConnection>scm:svn:http://www.jrimum.org/svn/bopepo</developerConnection>
		<tag>HEAD</tag>
		<url>http://www.jrimum.org/svn/bopepo</url>
	</scm>

	<developers>
		<developer>
			<name>Gilmar P. S. L.</name>
			<email>gilmatryx@gmail.com</email>
		</developer>
		<developer>
			<name>Misael Barreto</name>
			<email>misaelbarreto@gmail.com</email>
		</developer>
		<developer>
			<name>Rômulo Augusto</name>
			<email>romulomail@gmail.com</email>
		</developer>
	</developers>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	</properties>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
			<resource>
				<directory>src/examples/resources</directory>
			</resource>
		</resources>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>2.7</version>
			</plugin>
		</plugins>
	</reporting>

	<dependencies>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jrimum</groupId>
			<artifactId>jrimum-domkee</artifactId>
			<version>0.2.3-20240509</version>
		</dependency>
		<dependency>
			<groupId>org.jrimum</groupId>
			<artifactId>jrimum-texgit</artifactId>
			<version>0.2.0-20140202</version>
		</dependency>
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
			<version>5.6.1</version>
			<exclusions>
				<exclusion>
					<artifactId>xml-apis</artifactId>
					<groupId>xml-apis</groupId>
				</exclusion>
				<exclusion>
					<artifactId>jfreechart</artifactId>
					<groupId>jfree</groupId>
				</exclusion>
				<exclusion>
					<artifactId>jdtcore</artifactId>
					<groupId>eclipse</groupId>
				</exclusion>
				<exclusion>
					<artifactId>jcommon</artifactId>
					<groupId>jfree</groupId>
				</exclusion>
				<exclusion>
					<artifactId>commons-digester</artifactId>
					<groupId>commons-digester</groupId>
				</exclusion>
				<exclusion>
					<artifactId>commons-logging</artifactId>
					<groupId>commons-logging</groupId>
				</exclusion>
				<exclusion>
					<artifactId>commons-collections</artifactId>
					<groupId>commons-collections</groupId>
				</exclusion>
				<exclusion>
					<artifactId>commons-beanutils</artifactId>
					<groupId>commons-beanutils</groupId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

</project>